### ISSUE TITLE
Filescan result never persisted for some dataelements

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-file-scan#135]
### Description of the bug

Multiple data elements with filescanresult 'Pending'. 
No errors are logged in relation tot he processing of the filescan for the data elements in the FileScan function. 

One theory was that there might be a time diff, as we have a number of log messages identifying all the dataelements where there is a timediff during file scan (which results in the scan being aborted). All these dataelements have a 'Clean' result in the db meaning they have been queued for a new scan by storage probably due to the blob having been updated. 

Something else must be the reason behind the Pending result.

Query to identify affected data elements.  Output can be used directly to trigger new filescan manually. 

```sql
select d.alternateid as dataElementId,
CONCAT(i.partyid, '/', i.alternateid) as instanceId, 
d.element->'Filename' as filename, 
element->'LastChanged' as timestamp,  
element->'BlobStoragePath' as blobstoragepath
FROM storage.dataelements d
JOIN storage.instances i ON d.instanceinternalid =i.id
where d.element @> '{ "FileScanResult": "Pending" }'
order by timestamp asc;
```

### Steps To Reproduce
happens sporadically, not sure how to reproduce

**Comment by HenningNormann** [comment]
https://github.com/Altinn/altinn-storage/pull/341

**Comment by acn-sbuad** [comment]
no new pending file scans in production after this was deployed. Closing
