### ISSUE TITLE
Define how to collect statistics

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-file-scan#41]
### Description

We would like statistics as to how many and how large files are scanned on behalf of a given app owner. 
This task includes defining how to best identify these numbers and  create a script that does so.

### Tasks

- [ ] identify key metrics
- [ ] Create script
- [ ] Document script in [Altinn Pedia ](https://pedia.altinn.cloud/altinn-3/ops/tasks/statistics/)

**Comment by SandGrainOne** [comment]
Not prioritized
