### ISSUE TITLE
Scan retries for blobs that no longer exist

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-file-scan#43]
### Description of the bug

 If an end user uploads a data elements and triggers a file scan, but deleted the file before the scan is completed, the dataElement will be retried 5 times without luck. 

Should be able to identify that blob no longer exists and stop execution. 

A bit of an edge case, but it can happen and result in an unnecessary loard on the system. Should be handled when time allows.

### Steps To Reproduce

1. Disable filescan function
2. Upload file to an app with filescan enabled
3. Delete file
4. Enable filescan function
5. See error i filescan function logs

**Comment by SandGrainOne** [comment]
Not prioritized as it doesn't happen often enough to be a serious issue.
